public enum SemanticConvention {
    public static let sessionId = "session.id"
    public static let attributeSamplingRatio = "launchdarkly.sampling.ratio"
    public static let launchdarklySdkVersion = "launchdarkly.sdk.version"
    public static let highlightProjectId = "highlight.project_id"
    public static let telemetryDistroName = "telemetry.distro.name"
    public static let telemetryDistroVersion = "telemetry.distro.version"
    public static let serviceName = "service.name"
    public static let serviceVersion = "service.version"
    public static let serviceNamespace = "service.namespace"
    public static let systemCpuUtilization = "system.cpu.utilization"
    public static let systemMemoryAppUsageBytes = "system.memory.app_usage_bytes"
    public static let systemMemoryAppTotalBytes = "system.memory.app_total_bytes"
    public static let systemMemoryWarning = "system.memory.memory_warning"
    public static let deviceModelName = "device.model.name"
    public static let deviceModelIdentifier = "device.model.identifier"
    public static let deviceManufacturer = "device.manufacturer"
    public static let osName = "os.name"
    public static let osType = "os.type"
    public static let osVersion = "os.version"
    public static let osDescription = "os.description"
}
