name: Manual Publish

on:
    workflow_dispatch:
        inputs:
            dry_run:
                description: "Is this a dry run. If so no package will be published."
                type: boolean
                required: true

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v4

            - name: Get CocoaPods token
              uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
              with:
                  aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
                  ssm_parameter_pairs: '/production/common/releasing/cocoapods/token = COCOAPODS_TRUNK_TOKEN'

            - name: Publish to CocoaPods
              uses: ./.github/actions/publish
              with:
                  dry_run: ${{ inputs.dry_run }}
