name: Run Release Please

on:
    push:
        branches: [main]

jobs:
    release-package:
        runs-on: ubuntu-latest
        outputs:
            releases_created: ${{ steps.release.outputs.releases_created }}
        permissions:
            id-token: write
            contents: write # Contents and pull-requests are for release-please to make releases.
            pull-requests: write
            issues: write
        steps:
            # Normally a workflow cannot trigger another workflow. For this workflow we need to run required checks.
            # Github determines that something is created by a workflow/bot based on the token.
            - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
              name: 'Get PAT'
              with:
                  aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
                  ssm_parameter_pairs: '/production/common/releasing/o11y_gh_pat = GITHUB_PAT'
            - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445
              id: release
              with:
                  token: ${{ env.GITHUB_PAT }}

            - uses: actions/checkout@v4
              if: ${{ steps.release.outputs.releases_created == 'true' }}
              with:
                  fetch-depth: 0 # If you only need the current version keep this.

    publish-pods:
        needs: release-package
        if: ${{ needs.release-package.outputs.releases_created == 'true' }}
        runs-on: macos-15
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
              name: 'Get CocoaPods token'
              with:
                  aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
                  ssm_parameter_pairs: '/production/common/releasing/cocoapods/token = COCOAPODS_TRUNK_TOKEN'
            - uses: ./.github/actions/publish
              with:
                  dry_run: 'false'
